container: 'rocker/r-ver:3.6.0'  

steps:
- bash: Rscript -e 'R.version'
- bash: Rscript -e "install.packages('Rcpp',dependencies=TRUE, destdir=\"./\", repos='http://cran.rstudio.com/')"
#build cppEDM with respective makefile
- script: make -C rEDMNew/cppEDM/src
#build the package and download
- script: make build
- script: make check
