
pool:
  vmImage: 'macos-10.13'

steps:
#only setup the visual studio environment if on windowz
  - script: |
      curl -fLo /tmp/R.pkg "https://cloud.r-project.org/bin/macosx/R-latest.pkg"
      sudo installer -pkg "/tmp/R.pkg" -target /
      rm /tmp/R.pkg
    displayName: 'Installing R'

  - script: R CMD build rEDMNew 
    displayName: 'building project'


  - script: R CMD INSTALL rEDMNew_*
    displayName: 'installing project'
