// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_testing
Rcpp::List rcpp_testing(Rcpp::DataFrame dataframe);
RcppExport SEXP _rEDMNew_rcpp_testing(SEXP dataframeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dataframe(dataframeSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_testing(dataframe));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rEDMNew_rcpp_testing", (DL_FUNC) &_rEDMNew_rcpp_testing, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_rEDMNew(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
